# # List taken from dplR:::latexify

substitutions <- list(
  diaeresis = c("̈", "\""),
  acute = c("́", "'"),
  dotabove = c("̇", "."),
  macron = c("̄", "="),
  circumflex = c("̂", "^"),
  grave = c("̀", "`"),
  tilde = c("̃",   "~"),
  doubleacute = c("̋", "H"),
  ringabove = c("̊",  "r"),
  breve = c("̆", "u"),
  caron = c("̌", "v"),
  invbreve = c("̑", "newtie"),
  macronbelow = c("̱", "b"),
  cedilla = c("̧", "c"),
  dotbelow = c("̣", "d"),
  tie = c("͡", "t"),
  ogonek = c("̨", "k")
)

substitutions = lapply(substitutions, function(X){
  c(paste0("\\1",X[1]),
  paste0("\\\\",X[2],"\\{([aeiouyw])\\}"))
})

substitutions <- c(substitutions, list(
  c("¡", "\\\\textexclamdown\\{\\}"),
  c("£", "\\\\pounds\\{\\}"),
  c("§", "\\\\S\\{\\}"),
  c("©", "\\\\copyright\\{\\}"),
  c("ª", "\\\\textordfeminine\\{\\}"),
  c("®", "\\\\textregistered\\{\\}"),
  c("¶", "\\\\P\\{\\}"),
  c("·", "\\\\textperiodcentered\\{\\}"),
  c("º", "\\\\textordmasculine\\{\\}"),
  c("¿", "\\\\textquestiondown\\{\\}"),
  c("–", "\\\\textendash\\{\\}"),
  c("—", "\\\\textemdash\\{\\}"),
  c("‘", "\\\\textquoteleft\\{\\}"),
  c("’", "\\\\textquoteright\\{\\}"),
  c("“", "\\\\textquotedblleft\\{\\}"),
  c("”", "\\\\textquotedblright\\{\\}"),
  c("†", "\\\\dag\\{\\}"),
  c("‡", "\\\\ddag\\{\\}"),
  c("•", "\\\\textbullet\\{\\}"),
  c("…", "\\\\dots\\{\\}"),
  c("™", "\\\\texttrademark\\{\\}"),
  c("␣", "\\\\textvisiblespace\\{\\}"),
  c("Æ", "\\\\AE\\{\\}"),
  c("æ", "\\\\ae\\{\\}"),
  c("Œ", "\\\\OE\\{\\}"),
  c("œ", "\\\\oe\\{\\}"),
  c("Ø", "\\\\O\\{\\}"),
  c("ø", "\\\\o\\{\\}"),
  c("Ł", "\\\\L\\{\\}"),
  c("ł", "\\\\l\\{\\}"),
  c("ß", "\\\\ss\\{\\}"),

  c("Ð", "\\\\DH\\{\\}"),
  c("ð", "\\\\dh\\{\\}"),
  c("Đ", "\\\\DJ\\{\\}"),
  c("đ", "\\\\dj\\{\\}"),
  c("Ŋ", "\\\\NG\\{\\}"),
  c("ŋ", "\\\\ng\\{\\}"),
  c("Þ", "\\\\TH\\{\\}"),
  c("þ", "\\\\th\\{\\}"),
  c("«", "\\\\guillemotleft\\{\\}"),
  c("»", "\\\\guillemotright\\{\\}"),
  c("‚", "\\\\quotesinglbase\\{\\}"),
  c("„", "\\\\quotedblbase\\{\\}"),
  c("‹", "\\\\guilsinglleft\\{\\}"),
  c("›", "\\\\guilsinglright\\{\\}"),
  
  c("∗", "\\\\textasteriskcentered\\{\\}"),
  c("‖", "\\\\textbardbl\\{\\}"),
  c("◯", "\\\\textbigcircle\\{\\}"),
  c("␢", "\\\\textblank\\{\\}"),
  c("¦", "\\\\textbrokenbar\\{\\}"),
  c("⁒", "\\\\textdiscount\\{\\}"),
  c("℮", "\\\\textestimated\\{\\}"),
  c("‽", "\\\\textinterrobang\\{\\}"),
  c("\u2e18", "\\\\textinterrobangdown\\{\\}"),
  c("№", "\\\\textnumero\\{\\}"),
  c("◦", "\\\\textopenbullet\\{\\}"),
  c("‰", "\\\\textperthousand\\{\\}"),
  c("‱", "\\\\textpertenthousand\\{\\}"),
  c("℞", "\\\\textrecipe\\{\\}"),
  c("※", "\\\\textreferencemark\\{\\}"),
  c("\u02f7", "\\\\texttildelow\\{\\}"),
  c("←", "\\\\textleftarrow\\{\\}"),
  c("↑", "\\\\textuparrow\\{\\}"),
  c("→", "\\\\textrightarrow\\{\\}"),
  c("↓", "\\\\textdownarrow\\{\\}"),
  c("〈", "\\\\textlangle\\{\\}"),
  c("〉", "\\\\textrangle\\{\\}"),
  c("〚", "\\\\textlbrackdbl\\{\\}"),
  c("〛", "\\\\textrbrackdbl\\{\\}"),
  c("⁅", "\\\\textlquill\\{\\}"),
  c("⁆", "\\\\textrquill\\{\\}"),
  c("℗", "\\\\textcircledP\\{\\}"),
  c("℠", "\\\\textservicemark\\{\\}"),
  c("℃", "\\\\textcelsius\\{\\}"),
  c("℧", "\\\\textmho\\{\\}"),
  c("µ", "\\\\textmu\\{\\}"),
  c("Ω",  "\\\\textohm\\{\\}"),
  c("฿", "\\\\textbaht\\{\\}"),
  c("¢", "\\\\textcent\\{\\}"),
  c("₡", "\\\\textcolonmonetary\\{\\}"),
  c("¤", "\\\\textcurrency\\{\\}"),
  c("₫", "\\\\textdong\\{\\}"),
  c("\u20b2", "\\\\textguarani\\{\\}"),
  c("₤", "\\\\textlira\\{\\}"),
  c("₦", "\\\\textnaira\\{\\}"),
  c("₱", "\\\\textpeso\\{\\}"),
  c("₩", "\\\\textwon\\{\\}"),
  c("¥", "\\\\textyen\\{\\}"),
  c("˝", "\\\\textacutedbl\\{\\}"),
  c("´", "\\\\textasciiacute\\{\\}"),
  c("¸", "\\\\c\\{\\}"),
  c("˘", "\\\\textasciibreve\\{\\}"),
  c("ˇ", "\\\\textasciicaron\\{\\}"),
  c("¨", "\\\\textasciidieresis\\{\\}"),
  c("¯", "\\\\textasciimacron\\{\\}"),
  c("°", "\\\\textdegree\\{\\}"),
  c("÷", "\\\\textdiv\\{\\}"),
  c("¼", "\\\\textonequarter\\{\\}"),
  c("½", "\\\\textonehalf\\{\\}"),
  c("¾", "\\\\textthreequarters\\{\\}"),
  c("×", "\\\\texttimes\\{\\}"),
  c("±", "\\\\textpm\\{\\}"),
  c("¹", "\\\\textonesuperior\\{\\}"),
  c("²", "\\\\texttwosuperior\\{\\}"),
  c("³", "\\\\textthreesuperior\\{\\}"),
  c("⁄", "\\\\textfractionsolidus\\{\\}"),
  c("√", "\\\\textsurd\\{\\}"),
  c("¬", "\\\\textlnot\\{\\}"),
  c("−", "\\\\textminus\\{\\}"),
  # acutes
  c("á", "\\'a"),
  c("é", "\\'e"),
  c("í", "\\'i"),
  c("ó", "\\'o"),
  c("ú", "\\'u"),
  # diaresis
  c("ä", "\\\"a"),
  c("ë", "\\\"e"),
  c("ï", "\\\"i"),
  c("ö", "\\\"o"),
  c("ü", "\\\"u")
))

detexify = function(text){
  for(sub in substitutions){
    text = gsub(sub[2],sub[1], text)
  }
  # remove extra brackets
  text = gsub("[{}]","",text)
  # remove extra slashes
  text = gsub("\\\\","",text)
  return(text)
}



